"""Clinical summary report for HLA-Unified V2.

Generates a clinical-grade report suitable for transplant programs,
immunology labs, and clinical documentation. Includes only loci
with sufficient confidence, marks ambiguous calls with GL Strings,
and provides a methodology statement.

IMPORTANT: This output is intended to aid clinical interpretation
but should not replace validated clinical-grade HLA typing assays
for transplant decision-making without appropriate validation.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path

from ..pipeline.runner import PipelineResult, LocusCall
from ..confidence.ambiguity_classifier import AmbiguityClassification, AmbiguityReason

logger = logging.getLogger(__name__)


@dataclass
class ClinicalLocusCall:
    """Clinical-grade call for a single locus."""
    locus: str
    allele1: str
    allele2: str
    g_group1: str
    g_group2: str
    confidence: str
    is_ambiguous: bool
    ambiguity_reason: str
    gl_string: str
    notes: list[str] = field(default_factory=list)


@dataclass
class ClinicalSummary:
    """Complete clinical summary report."""
    # Header
    report_id: str
    generated_at: str
    methodology: str
    # Database
    imgt_release: str
    tool_version: str
    # Calls
    loci_reported: list[str]
    loci_withheld: list[str]
    calls: dict[str, ClinicalLocusCall]
    # Overall
    overall_confidence: str
    warnings: list[str] = field(default_factory=list)
    disclaimer: str = ""


METHODOLOGY_STATEMENT = (
    "HLA typing performed using HLA-Unified v{version}, a multi-strategy "
    "computational pipeline combining alignment-based pre-filtering, "
    "iterative refinement, integer linear programming genotyping, "
    "variational Bayes posterior confidence estimation, k-mer validation, "
    "and optional targeted assembly. Reference database: IPD-IMGT/HLA "
    "release {imgt_release}. Sequencing modality: {data_type}."
)

DISCLAIMER = (
    "DISCLAIMER: This report was generated by a computational HLA typing "
    "pipeline. Results should be interpreted in conjunction with clinical "
    "context and may require confirmation by validated laboratory methods "
    "before use in clinical decision-making (e.g., transplant matching). "
    "This tool has not been cleared or approved by any regulatory authority "
    "for clinical diagnostic use."
)


class ClinicalReporter:
    """Generates clinical-grade summary reports."""

    def __init__(
        self,
        min_confidence: str = "MEDIUM",
        version: str = "2.0.0",
    ) -> None:
        self.min_confidence = min_confidence
        self.version = version
        self._confidence_order = {
            "HIGH": 3, "MEDIUM": 2, "LOW": 1, "VERY_LOW": 0,
        }
        self._min_conf_level = self._confidence_order.get(min_confidence, 2)

    def generate(
        self,
        result: PipelineResult,
        ambiguity: dict[str, AmbiguityClassification] | None = None,
        data_type: str = "short",
    ) -> ClinicalSummary:
        """Generate a clinical summary from pipeline results."""
        reported_calls: dict[str, ClinicalLocusCall] = {}
        reported_loci: list[str] = []
        withheld_loci: list[str] = []
        warnings: list[str] = []

        for locus in sorted(result.calls.keys()):
            call = result.calls[locus]
            conf_level = self._confidence_order.get(call.confidence, 0)

            if conf_level < self._min_conf_level or not call.allele1:
                withheld_loci.append(locus)
                warnings.append(
                    f"HLA-{locus}: withheld (confidence={call.confidence})"
                )
                continue

            reported_loci.append(locus)

            # Determine ambiguity
            is_ambiguous = False
            ambig_reason = ""
            notes: list[str] = []

            if ambiguity and locus in ambiguity:
                ac = ambiguity[locus]
                is_ambiguous = ac.is_ambiguous
                ambig_reason = ac.primary_reason.value
                if is_ambiguous:
                    notes.append(f"Ambiguity: {ambig_reason}")
                    if ac.resolution_suggestion:
                        notes.append(f"Resolution: {ac.resolution_suggestion}")

            if call.is_novel:
                notes.append("Potential novel allele detected")
                warnings.append(
                    f"HLA-{locus}: potential novel allele "
                    f"(closest known: see novel_summary)"
                )

            if not call.kmer_concordant:
                notes.append("K-mer validation discordant — interpret with caution")
                warnings.append(f"HLA-{locus}: k-mer discordant")

            if call.flags:
                for flag in call.flags:
                    if flag not in ("homozygous",):
                        notes.append(f"Flag: {flag}")

            reported_calls[locus] = ClinicalLocusCall(
                locus=locus,
                allele1=call.allele1,
                allele2=call.allele2,
                g_group1=call.g_group1,
                g_group2=call.g_group2,
                confidence=call.confidence,
                is_ambiguous=is_ambiguous,
                ambiguity_reason=ambig_reason,
                gl_string=call.gl_string,
                notes=notes,
            )

        # Overall confidence
        if not reported_calls:
            overall = "INSUFFICIENT"
        elif all(c.confidence == "HIGH" for c in reported_calls.values()):
            overall = "HIGH"
        elif any(c.confidence == "HIGH" for c in reported_calls.values()):
            overall = "MIXED"
        else:
            overall = "MODERATE"

        methodology = METHODOLOGY_STATEMENT.format(
            version=self.version,
            imgt_release=result.imgt_release,
            data_type=data_type,
        )

        return ClinicalSummary(
            report_id=f"HLA-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
            generated_at=datetime.now(timezone.utc).isoformat(),
            methodology=methodology,
            imgt_release=result.imgt_release,
            tool_version=self.version,
            loci_reported=reported_loci,
            loci_withheld=withheld_loci,
            calls=reported_calls,
            overall_confidence=overall,
            warnings=warnings,
            disclaimer=DISCLAIMER,
        )

    def write_clinical_json(
        self, summary: ClinicalSummary, output_dir: Path,
    ) -> Path:
        """Write clinical summary as JSON."""
        path = output_dir / "clinical_summary.json"

        data = {
            "report_id": summary.report_id,
            "generated_at": summary.generated_at,
            "disclaimer": summary.disclaimer,
            "methodology": summary.methodology,
            "database": {
                "imgt_release": summary.imgt_release,
                "tool_version": summary.tool_version,
            },
            "summary": {
                "overall_confidence": summary.overall_confidence,
                "loci_reported": summary.loci_reported,
                "loci_withheld": summary.loci_withheld,
                "n_reported": len(summary.loci_reported),
                "n_withheld": len(summary.loci_withheld),
            },
            "calls": {
                locus: asdict(call)
                for locus, call in summary.calls.items()
            },
            "warnings": summary.warnings,
        }

        path.write_text(json.dumps(data, indent=2))
        logger.info("Clinical summary written to %s", path)
        return path

    def write_clinical_text(
        self, summary: ClinicalSummary, output_dir: Path,
    ) -> Path:
        """Write human-readable clinical summary."""
        path = output_dir / "clinical_summary.txt"

        lines = [
            "=" * 72,
            "HLA TYPING REPORT",
            "=" * 72,
            "",
            f"Report ID: {summary.report_id}",
            f"Generated: {summary.generated_at}",
            f"Database:  IPD-IMGT/HLA {summary.imgt_release}",
            f"Tool:      HLA-Unified v{summary.tool_version}",
            "",
            "-" * 72,
            "RESULTS",
            "-" * 72,
            "",
            f"{'Locus':<12} {'Allele 1':<20} {'Allele 2':<20} {'Conf':<8} {'Ambig'}",
            f"{'-'*12} {'-'*20} {'-'*20} {'-'*8} {'-'*10}",
        ]

        for locus in summary.loci_reported:
            call = summary.calls[locus]
            ambig_marker = "*" if call.is_ambiguous else ""
            lines.append(
                f"HLA-{call.locus:<8} {call.allele1:<20} {call.allele2:<20} "
                f"{call.confidence:<8} {ambig_marker}{call.ambiguity_reason}"
            )

        if summary.loci_withheld:
            lines.extend([
                "",
                f"Withheld loci (insufficient confidence): "
                f"{', '.join('HLA-' + l for l in summary.loci_withheld)}",
            ])

        if any(c.is_ambiguous for c in summary.calls.values()):
            lines.extend(["", "* = ambiguous call; see ambiguity report for alternatives"])

        if summary.warnings:
            lines.extend([
                "",
                "-" * 72,
                "WARNINGS",
                "-" * 72,
            ])
            for w in summary.warnings:
                lines.append(f"  - {w}")

        lines.extend([
            "",
            "-" * 72,
            "METHODOLOGY",
            "-" * 72,
            "",
            summary.methodology,
            "",
            "-" * 72,
            "DISCLAIMER",
            "-" * 72,
            "",
            summary.disclaimer,
            "",
            "=" * 72,
        ])

        path.write_text("\n".join(lines))
        logger.info("Clinical text report written to %s", path)
        return path
