"""Assay-specific presets and use-case profiles for HLA-Unified V2.

Consolidates all scattered parameter definitions (fast_mapper.ASSAY_CONFIGS,
iterative_refiner.ALIGNER_CONFIG, etc.) into a single source of truth.
"""

from __future__ import annotations

from .schema import AssayPreset, UseCaseProfile


# ---------------------------------------------------------------------------
# Assay presets: one per sequencing modality
# ---------------------------------------------------------------------------

ASSAY_PRESETS: dict[str, AssayPreset] = {
    "short": AssayPreset(
        name="short",
        description="Paired-end short-read WGS (Illumina)",
        minimap2_preset="sr",
        bowtie2_params=["--very-sensitive", "-k", "50", "--no-unal"],
        expected_coverage=30,
        min_coverage=5,
        extract_unmapped=True,
        focus_exons_only=False,
        max_prefilter_candidates=80,
        max_refined_candidates=20,
        confidence_threshold=0.90,
        assembly_confidence_trigger=0.80,
        phasing_min_het_depth=5,
        phasing_min_minor_af=0.15,
        phasing_min_het_sites=2,
        kmer_k=31,
        kmer_min_coverage=0.90,
        kmer_max_unexpected=0.30,
        assembler="megahit",
        assembly_timeout=300,
        assembly_genome_size="15k",
        min_informative_positions=5,
    ),
    "exome": AssayPreset(
        name="exome",
        description="Whole exome sequencing (WES)",
        minimap2_preset="sr",
        bowtie2_params=["--very-sensitive", "-k", "50", "--no-unal"],
        expected_coverage=60,
        min_coverage=10,
        extract_unmapped=True,
        focus_exons_only=True,
        max_prefilter_candidates=60,
        max_refined_candidates=15,
        confidence_threshold=0.90,
        assembly_confidence_trigger=0.85,
        phasing_min_het_depth=8,
        phasing_min_minor_af=0.15,
        phasing_min_het_sites=2,
        kmer_k=31,
        kmer_min_coverage=0.85,
        kmer_max_unexpected=0.35,
        assembler="megahit",
        assembly_timeout=300,
        assembly_genome_size="10k",
        min_informative_positions=3,
    ),
    "targeted_capture": AssayPreset(
        name="targeted_capture",
        description="Targeted HLA capture panel",
        minimap2_preset="sr",
        bowtie2_params=["--very-sensitive-local", "-k", "50", "--no-unal"],
        expected_coverage=200,
        min_coverage=20,
        extract_unmapped=False,
        focus_exons_only=False,
        max_prefilter_candidates=100,
        max_refined_candidates=25,
        confidence_threshold=0.95,
        assembly_confidence_trigger=0.90,
        phasing_min_het_depth=10,
        phasing_min_minor_af=0.20,
        phasing_min_het_sites=2,
        kmer_k=31,
        kmer_min_coverage=0.95,
        kmer_max_unexpected=0.20,
        assembler="megahit",
        assembly_timeout=300,
        assembly_genome_size="15k",
        min_informative_positions=5,
    ),
    "pacbio": AssayPreset(
        name="pacbio",
        description="PacBio CLR long reads",
        minimap2_preset="map-pb",
        bowtie2_params=[],
        expected_coverage=15,
        min_coverage=3,
        extract_unmapped=True,
        focus_exons_only=False,
        max_prefilter_candidates=60,
        max_refined_candidates=15,
        confidence_threshold=0.85,
        assembly_confidence_trigger=0.75,
        phasing_min_het_depth=3,
        phasing_min_minor_af=0.20,
        phasing_min_het_sites=1,
        kmer_k=21,
        kmer_min_coverage=0.80,
        kmer_max_unexpected=0.40,
        assembler="flye",
        assembly_timeout=600,
        assembly_genome_size="15k",
        min_informative_positions=3,
    ),
    "hifi": AssayPreset(
        name="hifi",
        description="PacBio HiFi high-fidelity long reads",
        minimap2_preset="map-hifi",
        bowtie2_params=[],
        expected_coverage=20,
        min_coverage=5,
        extract_unmapped=True,
        focus_exons_only=False,
        max_prefilter_candidates=60,
        max_refined_candidates=15,
        confidence_threshold=0.95,
        assembly_confidence_trigger=0.85,
        phasing_min_het_depth=3,
        phasing_min_minor_af=0.20,
        phasing_min_het_sites=1,
        kmer_k=31,
        kmer_min_coverage=0.92,
        kmer_max_unexpected=0.25,
        assembler="hifiasm",
        assembly_timeout=600,
        assembly_genome_size="15k",
        min_informative_positions=3,
    ),
    "ont": AssayPreset(
        name="ont",
        description="Oxford Nanopore long reads",
        minimap2_preset="map-ont",
        bowtie2_params=[],
        expected_coverage=20,
        min_coverage=5,
        extract_unmapped=True,
        focus_exons_only=False,
        max_prefilter_candidates=60,
        max_refined_candidates=15,
        confidence_threshold=0.85,
        assembly_confidence_trigger=0.75,
        phasing_min_het_depth=3,
        phasing_min_minor_af=0.20,
        phasing_min_het_sites=1,
        kmer_k=21,
        kmer_min_coverage=0.80,
        kmer_max_unexpected=0.40,
        assembler="flye",
        assembly_timeout=600,
        assembly_genome_size="15k",
        min_informative_positions=3,
    ),
    "rna": AssayPreset(
        name="rna",
        description="RNA-seq (coding sequence only)",
        minimap2_preset="splice",
        bowtie2_params=["--very-sensitive", "-k", "50"],
        expected_coverage=50,
        min_coverage=10,
        extract_unmapped=True,
        focus_exons_only=True,
        max_prefilter_candidates=60,
        max_refined_candidates=15,
        confidence_threshold=0.90,
        assembly_confidence_trigger=0.85,
        phasing_min_het_depth=8,
        phasing_min_minor_af=0.15,
        phasing_min_het_sites=2,
        kmer_k=31,
        kmer_min_coverage=0.85,
        kmer_max_unexpected=0.35,
        assembler="megahit",
        assembly_timeout=300,
        assembly_genome_size="10k",
        min_informative_positions=3,
    ),
}


# ---------------------------------------------------------------------------
# Use-case profiles
# ---------------------------------------------------------------------------

USE_CASE_PROFILES: dict[str, UseCaseProfile] = {
    "transplant": UseCaseProfile(
        name="transplant",
        description="Solid organ / HSCT donor-recipient matching. "
                    "Conservative reporting: only HIGH/MEDIUM confidence calls "
                    "at classical loci with strict reproducibility.",
        loci=["A", "B", "C", "DRB1", "DQB1", "DPB1"],
        min_confidence="HIGH",
        require_phasing=True,
        output_resolution=2,
        report_novel_alleles=True,
        clinical_summary=True,
        strict_reproducibility=True,
    ),
    "research": UseCaseProfile(
        name="research",
        description="Research-grade typing with maximum resolution. "
                    "Reports all loci including extended, accepts lower "
                    "confidence, and enables novel allele discovery.",
        loci=[
            "A", "B", "C", "DRB1", "DQA1", "DQB1", "DPA1", "DPB1",
            "DRB3", "DRB4", "DRB5", "DRA", "E", "F", "G",
        ],
        min_confidence="LOW",
        require_phasing=False,
        output_resolution="max",
        report_novel_alleles=True,
        clinical_summary=False,
        strict_reproducibility=False,
    ),
    "immuno_onc": UseCaseProfile(
        name="immuno_onc",
        description="Immuno-oncology neoantigen prediction. "
                    "Fast Class I typing for MHC binding prediction. "
                    "Tolerates moderate confidence for speed.",
        loci=["A", "B", "C"],
        min_confidence="MEDIUM",
        require_phasing=False,
        output_resolution=2,
        report_novel_alleles=False,
        clinical_summary=False,
        strict_reproducibility=False,
    ),
}
